openapi: '3.0.3'
info:
  title: STD23096
  version: '1.0.0'
servers:
  - url: https://localhost.STD23096.com      
paths:
  /customers:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer: 
      type: object
      properties:
        name:
          type: string
        age:
          type: integer